repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=95]
  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
  - repo: local
    hooks:
      - id: latex-format-all
        name: latex-format-all
        entry: latex-format-all
        language: system
        types:
          - tex
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types:
          - python
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        args:
          - --cov=melon
          - --cov-report=xml
        language: system
        pass_filenames: false
        always_run: true
